// src/components/EnhancedFileBrowser.tsx
import React, { useState, useCallback, type FC } from 'react';
import {
  Search, Filter, Grid3X3, List, FolderOpen, File, ChevronDown,
  ChevronRight, X, Check, Clock, HardDrive, Tag, Layers,
  ArrowUpDown, MoreVertical, Eye, EyeOff, Download, Trash2
} from 'lucide-react';
// @ts-ignore - missing hook
import { useFileBrowserFilters } from '../hooks/useFileBrowserFilters';
// @ts-ignore - missing hook
import { useOptimizedVirtualScroll, useFileSelection } from '../hooks/useOptimizedVirtualScroll';
import './EnhancedFileBrowser.css';

interface EnhancedFileBrowserProps {
  files: Array<{
    name: string;
    size: number;
    path: string;
    extension: string;
    category: string;
    subcategory?: string;
    semantic_tags?: string[];
    modified?: Date;
    created?: Date;
  }>;
  categories?: { [key: string]: { count: number; size: number } };
  onFileAction?: (action: string, file: any) => void;
}

interface ViewState {
  searchQuery: string;
  sortBy: 'name' | 'size' | 'modified' | 'category' | 'extension';
  sortOrder: 'asc' | 'desc';
  filters: {
    categories: string[];
    extensions: string[];
    sizeRange: [number, number];
    dateRange: [Date | null, Date | null];
  };
  viewMode: 'list' | 'grid' | 'tree' | 'compact';
  groupBy: 'none' | 'category' | 'extension' | 'size' | 'folder';
  showHidden: boolean;
  selectedFiles: Set<string>;
  expandedGroups: Set<string>;
}

export const EnhancedFileBrowser: FC<EnhancedFileBrowserProps> = ({
  files,
  categories,
  onFileAction
}) => {
  // Simplified state with optimized hooks
  const [showAdvancedFilters, setShowAdvancedFilters] = useState(false);
  const [focusedFile, setFocusedFile] = useState<string | null>(null);
  
  // View state
  const [viewState, setViewState] = useState<ViewState>({
    searchQuery: '',
    sortBy: 'name',
    sortOrder: 'asc',
    filters: {
      categories: [],
      extensions: [],
      sizeRange: [0, Number.MAX_SAFE_INTEGER],
      dateRange: [null, null]
    },
    viewMode: 'list',
    groupBy: 'none',
    showHidden: false,
    selectedFiles: new Set(),
    expandedGroups: new Set()
  });

  // Use optimized hooks
  const {
    filterOptions: filterOptionsValues,
    filteredFiles,
    sortedFiles,
    groupedFiles,
    formatSize
  } = useFileBrowserFilters(files, viewState);

  const {
    parentRef,
    virtualizer,
    scrollToIndex,
    visibleRange,
    isItemVisible
  } = useOptimizedVirtualScroll({
    count: sortedFiles.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => viewState.viewMode === 'compact' ? 32 : 56
  });

  const {
    selectedFiles,
    selectedCount,
    isAllSelected,
    toggleFileSelection,
    selectAll,
    clearSelection,
    isSelected
  } = useFileSelection({
    onSelectionChange: (newSelected) => {
      setViewState(prev => ({ ...prev, selectedFiles: newSelected }));
    }
  });

  // Update view state
  const updateViewState = useCallback((updates: Partial<ViewState>) => {
    setViewState(prev => ({ ...prev, ...updates }));
  }, []);

  // Render file item based on view mode
  const renderFileItem = useCallback((file: any, index: number) => {
    const isFocused = focusedFile === file.path;

    if (viewState.viewMode === 'compact') {
      return (
        <div
          key={file.path}
          className={`compact-file-item ${isSelected(file.path) ? 'selected' : ''} ${isFocused ? 'focused' : ''}`}
          onClick={() => toggleFileSelection(file.path, index, false)}
          onDoubleClick={() => onFileAction?.('open', file)}
        >
          <input
            type="checkbox"
            checked={isSelected(file.path)}
            onChange={(e) => {
              e.stopPropagation();
              toggleFileSelection(file.path, index, true);
            }}
            onClick={(e) => e.stopPropagation()}
          />
          <File size={14} />
          <span className="file-name">{file.name}</span>
          <span className="file-size">{formatSize(file.size)}</span>
          <span className="file-category">{file.category}</span>
        </div>
      );
    }

    if (viewState.viewMode === 'grid') {
      return (
        <div
          key={file.path}
          className={`grid-file-item ${isSelected(file.path) ? 'selected' : ''}`}
          onClick={() => toggleFileSelection(file.path, index, false)}
        >
          <div className="file-icon">
            <File size={24} />
          </div>
          <div className="file-info">
            <div className="file-name" title={file.name}>{file.name}</div>
            <div className="file-meta">
              <span>{formatSize(file.size)}</span>
              <span className="category-tag">{file.category}</span>
            </div>
          </div>
          <input
            type="checkbox"
            checked={isSelected(file.path)}
            onChange={(e) => {
              e.stopPropagation();
              toggleFileSelection(file.path, index, true);
            }}
            className="file-checkbox"
          />
        </div>
      );
    }

    // List view (default)
    return (
      <div
        key={file.path}
        className={`list-file-item ${isSelected(file.path) ? 'selected' : ''} ${isFocused ? 'focused' : ''}`}
        onClick={() => toggleFileSelection(file.path, index, false)}
      >
        <input
          type="checkbox"
          checked={isSelected(file.path)}
          onChange={(e) => {
            e.stopPropagation();
            toggleFileSelection(file.path, index, true);
          }}
        />
        <File size={18} />
        <div className="file-details">
          <div className="file-name">{file.name}</div>
          <div className="file-path">{file.path}</div>
          {file.semantic_tags && file.semantic_tags.length > 0 && (
            <div className="semantic-tags">
              {file.semantic_tags.slice(0, 3).map((tag, idx) => (
                <span key={idx} className="semantic-tag">{tag}</span>
              ))}
              {file.semantic_tags.length > 3 && (
                <span className="semantic-tag more">+{file.semantic_tags.length - 3}</span>
              )}
            </div>
          )}
        </div>
        <span className="file-size">{formatSize(file.size)}</span>
        <span className="file-extension">{file.extension || 'none'}</span>
        <span className="file-category">
          {file.category}
          {file.subcategory && file.subcategory !== file.category && (
            <span className="subcategory"> / {file.subcategory}</span>
          )}
        </span>
        <div className="file-actions">
          <button onClick={(e) => { e.stopPropagation(); onFileAction?.('open', file); }} title="Open file">
            <Eye size={14} />
          </button>
          <button onClick={(e) => { e.stopPropagation(); onFileAction?.('delete', file); }} title="Delete file">
            <Trash2 size={14} />
          </button>
        </div>
      </div>
    );
  }, [viewState.viewMode, focusedFile, isSelected, toggleFileSelection, formatSize, onFileAction]);

  return (
    <div className="enhanced-file-browser">
      {/* Header with stats and controls */}
      <div className="browser-header">
        <div className="header-top">
          <div className="title-section">
            <h3>File Explorer</h3>
            <div className="stats">
              <span className="stat">
                <HardDrive size={14} />
                {filteredFiles.length.toLocaleString()} files
              </span>
              <span className="stat">
                {formatSize(filteredFiles.reduce((sum, f) => sum + f.size, 0))}
              </span>
              <span className="stat">
                <Layers size={14} />
                {Object.keys(groupedFiles).length} groups
              </span>
            </div>
          </div>
          
          <div className="view-controls">
            <div className="view-mode-buttons">
              <button
                onClick={() => updateViewState({ viewMode: 'list' })}
                className={viewState.viewMode === 'list' ? 'active' : ''}
                title="List view"
              >
                <List size={16} />
              </button>
              <button
                onClick={() => updateViewState({ viewMode: 'grid' })}
                className={viewState.viewMode === 'grid' ? 'active' : ''}
                title="Grid view"
              >
                <Grid3X3 size={16} />
              </button>
              <button
                onClick={() => updateViewState({ viewMode: 'compact' })}
                className={viewState.viewMode === 'compact' ? 'active' : ''}
                title="Compact view"
              >
                <Layers size={16} />
              </button>
            </div>
            
            <button
              onClick={() => setShowAdvancedFilters(!showAdvancedFilters)}
              className={`filter-toggle ${showAdvancedFilters ? 'active' : ''}`}
            >
              <Filter size={16} />
              Filters
            </button>
            
            <button
              onClick={() => updateViewState({ showHidden: !viewState.showHidden })}
              className={viewState.showHidden ? 'active' : ''}
            >
              {viewState.showHidden ? <EyeOff size={16} /> : <Eye size={16} />}
            </button>
          </div>
        </div>

        {/* Search and quick filters */}
        <div className="search-section">
          <div className="search-bar">
            <Search size={16} />
            <input
              type="text"
              placeholder="Search files by name or path..."
              value={viewState.searchQuery}
              onChange={(e) => updateViewState({ searchQuery: e.target.value })}
              aria-label="Search files"
              title="Search files"
            />
            {viewState.searchQuery && (
              <button onClick={() => updateViewState({ searchQuery: '' })} title="Clear search">
                <X size={14} />
              </button>
            )}
          </div>
          
          <div className="quick-filters">
            <select
              value={viewState.groupBy}
              onChange={(e) => updateViewState({ groupBy: e.target.value as any })}
              aria-label="Group files by"
              title="Group files by"
            >
              <option value="none">No Grouping</option>
              <option value="category">Group by Category</option>
              <option value="extension">Group by Extension</option>
              <option value="size">Group by Size</option>
              <option value="folder">Group by Folder</option>
            </select>
            
            <select
              value={`${viewState.sortBy}-${viewState.sortOrder}`}
              onChange={(e) => {
                const [sortBy, sortOrder] = e.target.value.split('-');
                updateViewState({ sortBy: sortBy as any, sortOrder: sortOrder as any });
              }}
              aria-label="Sort files"
              title="Sort files"
            >
              <option value="name-asc">Name (A-Z)</option>
              <option value="name-desc">Name (Z-A)</option>
              <option value="size-asc">Size (Smallest)</option>
              <option value="size-desc">Size (Largest)</option>
              <option value="modified-desc">Recently Modified</option>
              <option value="modified-asc">Oldest First</option>
              <option value="category-asc">Category (A-Z)</option>
            </select>
          </div>
        </div>
      </div>

      {/* Advanced Filters Panel */}
      {showAdvancedFilters && (
        <div className="advanced-filters">
          <div className="filter-section">
            <h4>Categories</h4>
            <div className="filter-options">
              {(filterOptionsValues?.categories || []).map(category => (
                <label key={category} className="filter-option">
                  <input
                    type="checkbox"
                    checked={viewState.filters.categories.includes(category)}
                    onChange={(e) => {
                      const newCategories = e.target.checked
                        ? [...viewState.filters.categories, category]
                        : viewState.filters.categories.filter(c => c !== category);
                      updateViewState({
                        filters: { ...viewState.filters, categories: newCategories }
                      });
                    }}
                  />
                  <span>{category}</span>
                  <span className="count">
                    {categories?.[category]?.count || 0}
                  </span>
                </label>
              ))}
            </div>
          </div>
          
          <div className="filter-section">
            <h4>Extensions</h4>
            <div className="filter-options">
              {(filterOptionsValues?.extensions || []).slice(0, 10).map(extension => (
                <label key={extension} className="filter-option">
                  <input
                    type="checkbox"
                    checked={viewState.filters.extensions.includes(extension)}
                    onChange={(e) => {
                      const newExtensions = e.target.checked
                        ? [...viewState.filters.extensions, extension]
                        : viewState.filters.extensions.filter(e => e !== extension);
                      updateViewState({
                        filters: { ...viewState.filters, extensions: newExtensions }
                      });
                    }}
                  />
                  <span>.{extension}</span>
                </label>
              ))}
              {(filterOptionsValues?.extensions?.length || 0) > 10 && (
                <button className="show-more">
                  +{(filterOptionsValues?.extensions?.length || 0) - 10} more
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Selection Toolbar */}
      {selectedCount > 0 && (
        <div className="selection-toolbar">
          <div className="selection-info">
            <Check size={16} />
            {selectedCount} files selected
          </div>
          <div className="selection-actions">
            <button onClick={() => selectAll(sortedFiles)}>Select All Visible</button>
            <button onClick={clearSelection}>Clear Selection</button>
            {onFileAction && (
              <>
                <button onClick={() => onFileAction('delete', Array.from(selectedFiles))}>
                  <Trash2 size={14} />
                  Delete
                </button>
                <button onClick={() => onFileAction('export', Array.from(selectedFiles))}>
                  <Download size={14} />
                  Export
                </button>
              </>
            )}
          </div>
        </div>
      )}

      {/* File Display */}
      <div className="file-display">
        {viewState.groupBy === 'none' ? (
          // Ungrouped view with virtual scrolling
          <div ref={parentRef} className="virtual-scroll-container">
            <div style={{ height: virtualizer.getTotalSize(), position: 'relative' }}>
              {virtualizer.getVirtualItems().map((virtualItem) => {
                const file = sortedFiles[virtualItem.index];
                return (
                  <div
                    key={virtualItem.key}
                    className="virtual-file-item"
                    style={{
                      ...virtualItem.style,
                      transform: `translateY(${virtualItem.start}px)`
                    }}
                  >
                    {renderFileItem(file, virtualItem.index)}
                  </div>
                );
              })}
            </div>
          </div>
        ) : (
          // Grouped view
          <div className="grouped-files">
            {Object.entries(groupedFiles).map(([groupName, groupFiles]) => {
              const isExpanded = viewState.expandedGroups.has(groupName);
              // @ts-ignore - groupFiles type
              const groupSize = groupFiles.reduce((sum: number, f: any) => sum + f.size, 0);
              
              return (
                <div key={groupName} className="file-group">
                  <div
                    className="group-header"
                    // @ts-ignore - toggleGroupExpansion
                    onClick={() => toggleGroupExpansion(groupName)}
                  >
                    <div className="group-toggle">
                      {isExpanded ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                    </div>
                    <div className="group-info">
                      <FolderOpen size={16} />
                      <span className="group-name">{groupName || 'Root'}</span>
                      <span className="group-stats">
                        {/* @ts-ignore - groupFiles type */}
                        {(groupFiles as any).length} files • {formatSize(groupSize)}
                      </span>
                    </div>
                  </div>
                  
                  {isExpanded && (
                    <div className="group-content">
                      {/* @ts-ignore - groupFiles type */}
                      {(groupFiles as any).map((file: any, index: number) => renderFileItem(file, index))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default EnhancedFileBrowser;

// src/components/vue/file-browser/EnhancedFileBrowser.vue
<template>
  <div class="enhanced-file-browser">
    <!-- Header -->
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-3">
        <FolderOpen class="w-6 h-6 text-blue-400" />
        <div>
          <h2 class="text-xl font-semibold">File Browser</h2>
          <p class="text-sm text-gray-400">{{ filteredFiles.length }} files</p>
        </div>
      </div>
      <div class="flex gap-2">
        <button
          :class="[
            'p-2 rounded-lg transition-colors',
            viewState.viewMode === 'list' ? 'bg-blue-600 text-white' : 'bg-gray-800 text-gray-400',
          ]"
          @click="viewState.viewMode = 'list'"
        >
          <List class="w-4 h-4" />
        </button>
        <button
          :class="[
            'p-2 rounded-lg transition-colors',
            viewState.viewMode === 'grid' ? 'bg-blue-600 text-white' : 'bg-gray-800 text-gray-400',
          ]"
          @click="viewState.viewMode = 'grid'"
        >
          <Grid3X3 class="w-4 h-4" />
        </button>
      </div>
    </div>

    <!-- Search and Filters -->
    <div class="flex gap-2 mb-4">
      <div class="relative flex-1">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
        <input
          v-model="viewState.searchQuery"
          type="text"
          placeholder="Search files..."
          class="w-full pl-10 pr-4 py-2 bg-gray-800 border border-gray-700 rounded-lg focus:outline-none focus:border-blue-500 text-white"
        />
      </div>
      <button
        class="flex items-center gap-2 px-4 py-2 bg-gray-800 text-white rounded-lg hover:bg-gray-700 transition-colors"
        @click="showAdvancedFilters = !showAdvancedFilters"
      >
        <Filter class="w-4 h-4" />
        <span>Filters</span>
      </button>
    </div>

    <!-- Advanced Filters -->
    <div v-if="showAdvancedFilters" class="bg-gray-800 border border-gray-700 rounded-lg p-4 mb-4">
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm text-gray-400 mb-2">Sort By</label>
          <select
            v-model="viewState.sortBy"
            class="w-full bg-gray-700 border border-gray-600 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500"
          >
            <option value="name">Name</option>
            <option value="size">Size</option>
            <option value="modified">Modified</option>
            <option value="category">Category</option>
            <option value="extension">Extension</option>
          </select>
        </div>
        <div>
          <label class="block text-sm text-gray-400 mb-2">Sort Order</label>
          <button
            class="w-full flex items-center justify-center gap-2 px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white hover:bg-gray-600 transition-colors"
            @click="viewState.sortOrder = viewState.sortOrder === 'asc' ? 'desc' : 'asc'"
          >
            <ArrowUpDown class="w-4 h-4" />
            <span>{{ viewState.sortOrder === "asc" ? "Ascending" : "Descending" }}</span>
          </button>
        </div>
        <div>
          <label class="block text-sm text-gray-400 mb-2">Group By</label>
          <select
            v-model="viewState.groupBy"
            class="w-full bg-gray-700 border border-gray-600 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500"
          >
            <option value="none">None</option>
            <option value="category">Category</option>
            <option value="extension">Extension</option>
            <option value="size">Size</option>
            <option value="folder">Folder</option>
          </select>
        </div>
        <div>
          <label class="block text-sm text-gray-400 mb-2">View</label>
          <button
            :class="[
              'w-full flex items-center justify-center gap-2 px-4 py-2 rounded-lg transition-colors',
              viewState.showHidden ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300',
            ]"
            @click="viewState.showHidden = !viewState.showHidden"
          >
            <Eye v-if="viewState.showHidden" class="w-4 h-4" />
            <EyeOff v-else class="w-4 h-4" />
            <span>{{ viewState.showHidden ? "Show Hidden" : "Hide Hidden" }}</span>
          </button>
        </div>
      </div>
    </div>

    <!-- File List -->
    <div class="bg-gray-800 border border-gray-700 rounded-lg overflow-hidden">
      <!-- List View -->
      <div v-if="viewState.viewMode === 'list'" class="divide-y divide-gray-700">
        <div
          v-for="file in sortedFiles"
          :key="file.path"
          :class="[
            'flex items-center gap-3 p-3 cursor-pointer hover:bg-gray-700 transition-colors',
            viewState.selectedFiles.has(file.path) ? 'bg-blue-600/20' : '',
          ]"
          @click="selectFile(file.path)"
        >
          <File class="w-5 h-5 text-gray-400 shrink-0" />
          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium text-white truncate">
              {{ file.name }}
            </p>
            <p class="text-xs text-gray-400 truncate">
              {{ file.path }}
            </p>
          </div>
          <div class="flex items-center gap-4 shrink-0">
            <span class="text-sm text-gray-400">{{ formatSize(file.size) }}</span>
            <span class="text-xs px-2 py-1 bg-gray-700 rounded text-gray-300">{{
              file.category
            }}</span>
          </div>
        </div>
      </div>

      <!-- Grid View -->
      <div v-else class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4 p-4">
        <div
          v-for="file in sortedFiles"
          :key="file.path"
          :class="[
            'bg-gray-700 rounded-lg p-4 cursor-pointer hover:bg-gray-600 transition-colors',
            viewState.selectedFiles.has(file.path) ? 'ring-2 ring-blue-500' : '',
          ]"
          @click="selectFile(file.path)"
        >
          <File class="w-8 h-8 text-gray-400 mx-auto mb-2" />
          <p class="text-sm font-medium text-white truncate text-center">
            {{ file.name }}
          </p>
          <p class="text-xs text-gray-400 text-center mt-1">
            {{ formatSize(file.size) }}
          </p>
        </div>
      </div>

      <!-- Empty State -->
      <div v-if="sortedFiles.length === 0" class="text-center py-12 text-gray-400">
        <File class="w-12 h-12 mx-auto mb-4" />
        <p>No files found</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import {
  Search,
  Filter,
  Grid3X3,
  List,
  FolderOpen,
  File,
  ChevronDown,
  ChevronRight,
  X,
  Check,
  Clock,
  HardDrive,
  Tag,
  Layers,
  ArrowUpDown,
  MoreVertical,
  Eye,
  EyeOff,
  Download,
  Trash2,
} from "lucide-vue-next";

interface FileData {
  name: string;
  size: number;
  path: string;
  extension: string;
  category: string;
  subcategory?: string;
  semantic_tags?: string[];
  modified?: Date;
  created?: Date;
}

interface EnhancedFileBrowserProps {
  files: FileData[];
  categories?: Record<string, { count: number; size: number }>;
  onFileAction?: (action: string, file: FileData) => void;
}

const props = withDefaults(defineProps<EnhancedFileBrowserProps>(), {
  files: () => [],
  categories: () => ({}),
  onFileAction: () => {},
});

const showAdvancedFilters = ref(false);

const viewState = ref({
  searchQuery: "",
  sortBy: "name" as "name" | "size" | "modified" | "category" | "extension",
  sortOrder: "asc" as "asc" | "desc",
  filters: {
    categories: [] as string[],
    extensions: [] as string[],
    sizeRange: [0, Number.MAX_SAFE_INTEGER] as [number, number],
    dateRange: [null, null] as [Date | null, Date | null],
  },
  viewMode: "list" as "list" | "grid" | "tree" | "compact",
  groupBy: "none" as "none" | "category" | "extension" | "size" | "folder",
  showHidden: false,
  selectedFiles: new Set<string>(),
  expandedGroups: new Set<string>(),
});

const filteredFiles = computed(() => {
  let result = [...props.files];

  // Apply search filter
  if (viewState.value.searchQuery) {
    const query = viewState.value.searchQuery.toLowerCase();
    result = result.filter(
      (file) =>
        file.name.toLowerCase().includes(query) ||
        file.path.toLowerCase().includes(query) ||
        file.category.toLowerCase().includes(query)
    );
  }

  // Apply category filter
  if (viewState.value.filters.categories.length > 0) {
    result = result.filter((file) => viewState.value.filters.categories.includes(file.category));
  }

  // Apply extension filter
  if (viewState.value.filters.extensions.length > 0) {
    result = result.filter((file) => viewState.value.filters.extensions.includes(file.extension));
  }

  // Apply size filter
  result = result.filter(
    (file) =>
      file.size >= viewState.value.filters.sizeRange[0] &&
      file.size <= viewState.value.filters.sizeRange[1]
  );

  return result;
});

const sortedFiles = computed(() => {
  const result = [...filteredFiles.value];

  result.sort((a, b) => {
    let comparison = 0;

    switch (viewState.value.sortBy) {
      case "name":
        comparison = a.name.localeCompare(b.name);
        break;
      case "size":
        comparison = a.size - b.size;
        break;
      case "modified":
        comparison = (a.modified?.getTime() || 0) - (b.modified?.getTime() || 0);
        break;
      case "category":
        comparison = a.category.localeCompare(b.category);
        break;
      case "extension":
        comparison = a.extension.localeCompare(b.extension);
        break;
    }

    return viewState.value.sortOrder === "asc" ? comparison : -comparison;
  });

  return result;
});

const formatSize = (bytes: number): string => {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
};

const selectFile = (path: string) => {
  if (viewState.value.selectedFiles.has(path)) {
    viewState.value.selectedFiles.delete(path);
  } else {
    viewState.value.selectedFiles.add(path);
  }
};
</script>

<style scoped>
.enhanced-file-browser {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
</style>
