// src/components/vue/visualization/ActionablePrediction.vue
<template>
  <div class="actionable-prediction-container">
    <!-- Dependency Analysis Modal -->
    <div v-if="showDependencyAnalysis && dependencyAnalysis" class="actionable-modal-overlay">
      <div class="actionable-modal">
        <div class="actionable-modal-header">
          <h2 class="actionable-modal-title">Dependency Impact Analysis</h2>
          <button
            class="actionable-close-btn"
            aria-label="Close dependency analysis"
            @click="showDependencyAnalysis = false"
          >
            <X :size="20" />
          </button>
        </div>
        <DependencyImpactAnalyzer
          :analysis="dependencyAnalysis"
          :loading="analyzingDependencies"
          @execute-action="executeActionWithConfirmation"
        />
      </div>
    </div>

    <div v-if="!insights || insights.length === 0" class="no-insights">
      <BrainCircuit :size="48" class="actionable-no-insights-icon" />
      <h3 class="actionable-no-insights-text">No Actionable Insights Available</h3>
      <p class="actionable-no-insights-text">
        Run more analyses to generate actionable predictions
      </p>
    </div>

    <template v-else>
      <div
        v-for="(insight, index) in insights"
        :key="index"
        class="glass-panel actionable-category-panel"
      >
        <!-- Header -->
        <div class="actionable-category-header">
          <div class="actionable-category-icon">
            <component
              :is="getCategoryIcon(extractCategoryFromReasoning(insight.reasoning))"
              :size="16"
            />
          </div>
          <h4 class="actionable-category-title">
            {{
              extractCategoryFromReasoning(insight.reasoning).charAt(0).toUpperCase() +
              extractCategoryFromReasoning(insight.reasoning).slice(1)
            }}
            Category
          </h4>
          <div class="actionable-category-stats">
            <div class="actionable-stat-item">
              <span class="actionable-stat-label">Files</span>
              <span class="actionable-stat-value">{{
                getFilesByCategory(extractCategoryFromReasoning(insight.reasoning)).length
              }}</span>
            </div>
            <div class="actionable-stat-item">
              <span class="actionable-stat-label">Total Size</span>
              <span class="actionable-stat-value">
                {{
                  (
                    getFilesByCategory(extractCategoryFromReasoning(insight.reasoning)).reduce(
                      (sum, f) => sum + f.size,
                      0
                    ) /
                    1024 /
                    1024
                  ).toFixed(1)
                }}MB
              </span>
            </div>
            <div class="actionable-stat-item">
              <span class="actionable-stat-label">Large Files</span>
              <span class="actionable-stat-value">{{
                getHighImpactFiles(extractCategoryFromReasoning(insight.reasoning)).length
              }}</span>
            </div>
          </div>
        </div>

        <!-- Primary Driver -->
        <div class="actionable-primary-driver">
          <h5 class="actionable-primary-driver-title">Primary Driver</h5>
          <div class="actionable-primary-driver-content">
            <AlertTriangle :size="14" class="actionable-primary-driver-icon" />
            {{ insight.reasoning.primaryFactor }}
          </div>
        </div>

        <!-- Actionable Items -->
        <div class="actionable-actions">
          <h5 class="actionable-actions-title">Recommended Actions</h5>
          <div class="actionable-actions-list">
            <div
              v-for="(action, actionIndex) in getRecommendedActions(
                insight,
                extractCategoryFromReasoning(insight.reasoning)
              )"
              :key="actionIndex"
              class="actionable-action-item"
            >
              <div class="actionable-action-icon">
                <component :is="getActionIcon(action.type)" :size="16" />
              </div>
              <div class="actionable-action-content">
                <h6 class="actionable-action-title">
                  {{ action.label }}
                </h6>
                <p class="actionable-action-description">
                  {{ action.description }}
                </p>
              </div>
              <div class="actionable-action-priority">
                <span :class="`actionable-priority-${action.priority}`">
                  {{ action.priority }}
                </span>
                <button
                  :disabled="
                    selectedAction ===
                      `${action.type}-${extractCategoryFromReasoning(insight.reasoning)}` ||
                    analyzingDependencies
                  "
                  class="actionable-execute-btn"
                  :style="{
                    background:
                      selectedAction ===
                      `${action.type}-${extractCategoryFromReasoning(insight.reasoning)}`
                        ? '#6b7280'
                        : '#3b82f6',
                    cursor:
                      selectedAction ===
                        `${action.type}-${extractCategoryFromReasoning(insight.reasoning)}` ||
                      analyzingDependencies
                        ? 'not-allowed'
                        : 'pointer',
                  }"
                  @click="
                    executeAction(
                      action.type,
                      extractCategoryFromReasoning(insight.reasoning),
                      insight
                    )
                  "
                >
                  <template
                    v-if="
                      selectedAction ===
                      `${action.type}-${extractCategoryFromReasoning(insight.reasoning)}`
                    "
                  >
                    <div class="spinner" />
                    {{
                      actionProgress[
                        `${action.type}-${extractCategoryFromReasoning(insight.reasoning)}`
                      ] || 0
                    }}%
                  </template>
                  <template v-else-if="analyzingDependencies">
                    <GitBranch :size="14" />
                    Analyzing Dependencies...
                  </template>
                  <template v-else>
                    <component :is="getActionIcon(action.type)" :size="16" />
                    Execute
                    <Shield
                      v-if="['delete', 'move', 'archive'].includes(action.type)"
                      :size="12"
                      style="margin-left: 0.25rem"
                    />
                  </template>
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- High Impact Files Preview -->
        <div v-if="getHighImpactFiles(extractCategoryFromReasoning(insight.reasoning)).length > 0">
          <h5 class="high-impact-title">
            High Impact Files (Top
            {{ getHighImpactFiles(extractCategoryFromReasoning(insight.reasoning)).length }})
          </h5>
          <div class="high-impact-files">
            <div
              v-for="(file, fileIndex) in getHighImpactFiles(
                extractCategoryFromReasoning(insight.reasoning)
              ).slice(0, 5)"
              :key="fileIndex"
              class="high-impact-file"
            >
              <component :is="getCategoryIcon(file.category || 'unknown')" :size="16" />
              <span class="file-name">{{ file.path?.split(/[/\\]/).pop() || file.name }}</span>
              <span class="file-size">{{ (file.size / (1024 * 1024)).toFixed(1) }}MB</span>
            </div>
            <div
              v-if="getHighImpactFiles(extractCategoryFromReasoning(insight.reasoning)).length > 5"
              class="more-files"
            >
              ... and
              {{ getHighImpactFiles(extractCategoryFromReasoning(insight.reasoning)).length - 5 }}
              more files
            </div>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import {
  AlertTriangle,
  GitBranch,
  AlertCircle,
  TrendingUp,
  Clock,
  Calendar,
  CheckCircle,
  X,
  ChevronDown,
  ChevronUp,
  Zap,
  Target,
  Archive,
  Trash2,
  FolderOpen,
  BrainCircuit,
  Download,
  Move,
  FileText,
  Image,
  Video,
  Music,
  Code,
  HardDrive,
  Shield,
} from "lucide-vue-next";
import DependencyImpactAnalyzer from "./DependencyImpactAnalyzer.vue";

interface PredictiveInsight {
  type: string;
  reasoning: {
    primaryFactor: string;
    contributingFactors: string[];
    trendAnalysis?: {
      direction: string;
    };
  };
}

interface ActionablePredictionProps {
  insights: PredictiveInsight[];
  onAction: (action: string, target: string, files?: any[]) => void;
  files: any[];
  categories: { [key: string]: any };
}

const props = defineProps<ActionablePredictionProps>();

const selectedAction = ref<string | null>(null);
const actionProgress = ref<{ [key: string]: number }>({});
const dependencyAnalysis = ref<any>(null);
const analyzingDependencies = ref(false);
const showDependencyAnalysis = ref(false);

const getCategoryIcon = (category: string) => {
  switch (category.toLowerCase()) {
    case "documents":
      return FileText;
    case "images":
      return Image;
    case "videos":
      return Video;
    case "audio":
      return Music;
    case "code":
      return Code;
    case "executables":
      return HardDrive;
    default:
      return FileText;
  }
};

const getActionIcon = (action: string) => {
  switch (action) {
    case "cleanup":
      return Trash2;
    case "organize":
      return FolderOpen;
    case "archive":
      return Archive;
    case "move":
      return Move;
    case "analyze":
      return BrainCircuit;
    default:
      return Target;
  }
};

const extractCategoryFromReasoning = (reasoning: any): string => {
  const primaryFactor = reasoning.primaryFactor.toLowerCase();
  const categories = [
    "documents",
    "images",
    "videos",
    "audio",
    "code",
    "executables",
    "system",
    "temp",
    "archives",
  ];

  for (const category of categories) {
    if (primaryFactor.includes(category)) {
      return category;
    }
  }

  for (const factor of reasoning.contributingFactors) {
    const factorLower = factor.toLowerCase();
    for (const category of categories) {
      if (factorLower.includes(category)) {
        return category;
      }
    }
  }

  return "unknown";
};

const getFilesByCategory = (category: string) => {
  return props.files.filter(
    (file) =>
      file.category?.toLowerCase() === category.toLowerCase() ||
      file.path?.toLowerCase().includes(category.toLowerCase())
  );
};

const getHighImpactFiles = (category: string, limit = 10) => {
  const categoryFiles = getFilesByCategory(category);
  return categoryFiles.sort((a, b) => (b.size || 0) - (a.size || 0)).slice(0, limit);
};

const executeAction = async (action: string, target: string, insight: PredictiveInsight) => {
  selectedAction.value = `${action}-${target}`;
  actionProgress.value = { ...actionProgress.value, [`${action}-${target}`]: 0 };

  try {
    if (["delete", "move", "archive"].includes(action)) {
      await analyzeDependencies(action, target, insight);
    }

    if (
      dependencyAnalysis.value &&
      (dependencyAnalysis.value.overallRisk === "critical" ||
        dependencyAnalysis.value.overallRisk === "high")
    ) {
      showDependencyAnalysis.value = true;
      return;
    }

    switch (action) {
      case "cleanup":
        await executeCleanup(target, insight);
        break;
      case "organize":
        await executeOrganization(target, insight);
        break;
      case "archive":
        await executeArchive(target, insight);
        break;
      case "analyze":
        await executeAnalysis(target, insight);
        break;
      default:
        console.log(`Unknown action: ${action} on ${target}`);
    }

    props.onAction(action, target, getFilesByCategory(target));
  } catch (error) {
    console.error(`Failed to execute ${action} on ${target}:`, error);
  } finally {
    selectedAction.value = null;
    actionProgress.value = { ...actionProgress.value, [`${action}-${target}`]: 100 };
  }
};

const analyzeDependencies = async (action: string, target: string, insight: PredictiveInsight) => {
  analyzingDependencies.value = true;

  try {
    // Placeholder for dependency analysis
    console.log("Analyzing dependencies for", action, target);
  } catch (error) {
    console.error("Failed to analyze dependencies:", error);
  } finally {
    analyzingDependencies.value = false;
  }
};

const executeActionWithConfirmation = async (action: string, alternative?: string) => {
  const actualAction = alternative || action;

  switch (actualAction) {
    case "cleanup":
      await executeCleanup(
        dependencyAnalysis.value?.targetFiles[0]?.split("/")[0] || "",
        {} as any
      );
      break;
    case "organize":
      await executeOrganization(
        dependencyAnalysis.value?.targetFiles[0]?.split("/")[0] || "",
        {} as any
      );
      break;
    case "archive":
      await executeArchive(
        dependencyAnalysis.value?.targetFiles[0]?.split("/")[0] || "",
        {} as any
      );
      break;
    case "move":
      await executeMove(dependencyAnalysis.value?.targetFiles[0]?.split("/")[0] || "", {} as any);
      break;
    default:
      console.log(`Executing alternative action: ${actualAction}`);
  }

  showDependencyAnalysis.value = false;
  dependencyAnalysis.value = null;
};

const executeCleanup = async (target: string, insight: PredictiveInsight) => {
  const targetFiles = getFilesByCategory(target);

  for (let i = 0; i <= 100; i += 10) {
    actionProgress.value = { ...actionProgress.value, [`cleanup-${target}`]: i };
    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  console.log(`Cleaned up ${targetFiles.length} files from ${target} category`);
};

const executeOrganization = async (target: string, insight: PredictiveInsight) => {
  const targetFiles = getFilesByCategory(target);

  for (let i = 0; i <= 100; i += 20) {
    actionProgress.value = { ...actionProgress.value, [`organize-${target}`]: i };
    await new Promise((resolve) => setTimeout(resolve, 150));
  }

  console.log(`Organized ${targetFiles.length} files in ${target} category`);
};

const executeArchive = async (target: string, insight: PredictiveInsight) => {
  const targetFiles = getHighImpactFiles(target);

  for (let i = 0; i <= 100; i += 25) {
    actionProgress.value = { ...actionProgress.value, [`archive-${target}`]: i };
    await new Promise((resolve) => setTimeout(resolve, 200));
  }

  console.log(`Archived ${targetFiles.length} large files from ${target} category`);
};

const executeAnalysis = async (target: string, insight: PredictiveInsight) => {
  for (let i = 0; i <= 100; i += 10) {
    actionProgress.value = { ...actionProgress.value, [`analyze-${target}`]: i };
    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  console.log(`Analyzed ${target} category for detailed insights`);
};

const executeMove = async (target: string, insight: PredictiveInsight) => {
  const targetFiles = getFilesByCategory(target);

  for (let i = 0; i <= 100; i += 20) {
    actionProgress.value = { ...actionProgress.value, [`move-${target}`]: i };
    await new Promise((resolve) => setTimeout(resolve, 150));
  }

  console.log(`Moved ${targetFiles.length} files from ${target} category`);
};

const getRecommendedActions = (insight: PredictiveInsight, category: string) => {
  const actions: {
    type: string;
    label: string;
    description: string;
    priority: "high" | "medium" | "low";
  }[] = [];

  switch (insight.type) {
    case "growth":
      if (insight.reasoning.trendAnalysis?.direction === "increasing") {
        actions.push({
          type: "cleanup",
          label: "Smart Cleanup",
          description: `Remove unnecessary ${category} files to slow growth`,
          priority: "high",
        });
        actions.push({
          type: "archive",
          label: "Archive Large Files",
          description: `Move large ${category} files to archive storage`,
          priority: "medium",
        });
      }
      break;

    case "cleanup":
      actions.push({
        type: "cleanup",
        label: "Quick Cleanup",
        description: `Remove temp and unnecessary ${category} files`,
        priority: "high",
      });
      break;

    case "organization":
      actions.push({
        type: "organize",
        label: "Auto-Organize",
        description: `Create subfolders and organize ${category} files`,
        priority: "medium",
      });
      break;

    case "security":
      actions.push({
        type: "analyze",
        label: "Security Scan",
        description: `Analyze ${category} files for security risks`,
        priority: "high",
      });
      break;
  }

  return actions;
};
</script>

<style scoped>
.actionable-prediction-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.no-insights {
  @apply flex flex-col items-center justify-center py-12 text-center;
}

.actionable-no-insights-icon {
  @apply text-gray-400 mb-4;
}

.actionable-no-insights-text {
  @apply text-gray-400;
}

.actionable-modal-overlay {
  @apply fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4;
}

.actionable-modal {
  @apply bg-gray-800 border border-gray-700 rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto;
}

.actionable-modal-header {
  @apply flex items-center justify-between p-4 border-b border-gray-700;
}

.actionable-modal-title {
  @apply text-lg font-semibold text-white;
}

.actionable-close-btn {
  @apply text-gray-400 hover:text-white transition-colors;
}

.glass-panel {
  @apply bg-gray-800/50 backdrop-blur-sm border border-gray-700 rounded-lg p-4;
}

.actionable-category-panel {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.actionable-category-header {
  @apply flex items-center gap-3 pb-4 border-b border-gray-700;
}

.actionable-category-icon {
  @apply text-blue-400;
}

.actionable-category-title {
  @apply text-base font-semibold text-white;
}

.actionable-category-stats {
  @apply flex gap-4 ml-auto;
}

.actionable-stat-item {
  @apply flex flex-col;
}

.actionable-stat-label {
  @apply text-xs text-gray-400;
}

.actionable-stat-value {
  @apply text-sm font-medium text-white;
}

.actionable-primary-driver {
  @apply p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg;
}

.actionable-primary-driver-title {
  @apply text-xs font-medium text-yellow-400 mb-1;
}

.actionable-primary-driver-content {
  @apply flex items-center gap-2 text-sm text-white;
}

.actionable-primary-driver-icon {
  @apply text-yellow-400;
}

.actionable-actions {
  @apply space-y-3;
}

.actionable-actions-title {
  @apply text-sm font-medium text-white mb-2;
}

.actionable-actions-list {
  @apply space-y-2;
}

.actionable-action-item {
  @apply flex items-center gap-3 p-3 bg-gray-700/50 rounded-lg;
}

.actionable-action-icon {
  @apply text-gray-400;
}

.actionable-action-content {
  @apply flex-1;
}

.actionable-action-title {
  @apply text-sm font-medium text-white;
}

.actionable-action-description {
  @apply text-xs text-gray-400;
}

.actionable-action-priority {
  @apply flex items-center gap-2;
}

.actionable-priority-high {
  @apply px-2 py-1 bg-red-500/20 text-red-400 rounded text-xs font-medium;
}

.actionable-priority-medium {
  @apply px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded text-xs font-medium;
}

.actionable-priority-low {
  @apply px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs font-medium;
}

.actionable-execute-btn {
  @apply px-4 py-2 text-white rounded-lg font-bold flex items-center gap-2 text-sm;
}

.spinner {
  @apply w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin;
}

.high-impact-title {
  @apply text-sm font-medium text-white mb-2;
}

.high-impact-files {
  @apply grid gap-2 max-h-48 overflow-y-auto;
}

.high-impact-file {
  @apply flex items-center gap-2 p-2 bg-gray-700/30 rounded text-sm;
}

.file-name {
  @apply flex-1 text-white;
}

.file-size {
  @apply text-gray-400;
}

.more-files {
  @apply text-center text-gray-400 text-xs py-2;
}
</style>

// src/components/react/ActionablePrediction.tsx
import React, { useState, useCallback } from "react";
import type { FC } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import {
  AlertTriangle,
  GitBranch,
  AlertCircle,
  TrendingUp,
  Clock,
  Calendar,
  CheckCircle,
  X,
  ChevronDown,
  ChevronUp,
  Zap,
  Target,
  Archive,
  Trash2,
  FolderOpen,
  BrainCircuit,
  Download,
  Move,
  FileText,
  Image,
  Video,
  Music,
  Code,
  HardDrive,
  Shield,
} from "lucide-react";
import "./ActionablePrediction.css";
import { PredictiveInsight } from "./PredictionExplainer";
import { DependencyImpactAnalyzer } from "./DependencyImpactAnalyzer";
import { dependencyCheckerService } from "../services/DependencyCheckerService";

interface ActionablePredictionProps {
  insights: PredictiveInsight[];
  onAction: (action: string, target: string, files?: any[]) => void;
  files: any[];
  categories: { [key: string]: any };
}

const ActionablePrediction: FC<ActionablePredictionProps> = ({
  insights,
  onAction,
  files,
  categories,
}) => {
  const [selectedAction, setSelectedAction] = useState<string | null>(null);
  const [actionProgress, setActionProgress] = useState<{ [key: string]: number }>({});
  const [dependencyAnalysis, setDependencyAnalysis] = useState<any>(null);
  const [analyzingDependencies, setAnalyzingDependencies] = useState(false);
  const [showDependencyAnalysis, setShowDependencyAnalysis] = useState(false);

  const getCategoryIcon = (category: string) => {
    switch (category.toLowerCase()) {
      case "documents":
        return <FileText size={16} />;
      case "images":
        return <Image size={16} />;
      case "videos":
        return <Video size={16} />;
      case "audio":
        return <Music size={16} />;
      case "code":
        return <Code size={16} />;
      case "executables":
        return <HardDrive size={16} />;
      default:
        return <FileText size={16} />;
    }
  };

  const getActionIcon = (action: string) => {
    switch (action) {
      case "cleanup":
        return <Trash2 size={16} />;
      case "organize":
        return <FolderOpen size={16} />;
      case "archive":
        return <Archive size={16} />;
      case "move":
        return <Move size={16} />;
      case "analyze":
        return <BrainCircuit size={16} />;
      default:
        return <Target size={16} />;
    }
  };

  const extractCategoryFromReasoning = (reasoning: any): string => {
    // Extract category from primary factor or contributing factors
    const primaryFactor = reasoning.primaryFactor.toLowerCase();
    const categories = [
      "documents",
      "images",
      "videos",
      "audio",
      "code",
      "executables",
      "system",
      "temp",
      "archives",
    ];

    for (const category of categories) {
      if (primaryFactor.includes(category)) {
        return category;
      }
    }

    for (const factor of reasoning.contributingFactors) {
      const factorLower = factor.toLowerCase();
      for (const category of categories) {
        if (factorLower.includes(category)) {
          return category;
        }
      }
    }

    return "unknown";
  };

  const getFilesByCategory = (category: string) => {
    return files.filter(
      (file) =>
        file.category?.toLowerCase() === category.toLowerCase() ||
        file.path?.toLowerCase().includes(category.toLowerCase())
    );
  };

  const getHighImpactFiles = (category: string, limit: number = 10) => {
    const categoryFiles = getFilesByCategory(category);
    return categoryFiles.sort((a, b) => (b.size || 0) - (a.size || 0)).slice(0, limit);
  };

  const executeAction = async (action: string, target: string, insight: PredictiveInsight) => {
    setSelectedAction(`${action}-${target}`);
    setActionProgress((prev) => ({ ...prev, [`${action}-${target}`]: 0 }));

    try {
      // First analyze dependencies for high-risk actions
      if (["delete", "move", "archive"].includes(action)) {
        await analyzeDependencies(action, target, insight);
      }

      // If high-risk action, show dependency analysis first
      if (
        dependencyAnalysis &&
        (dependencyAnalysis.overallRisk === "critical" || dependencyAnalysis.overallRisk === "high")
      ) {
        setShowDependencyAnalysis(true);
        return; // Wait for user confirmation
      }

      // Execute the action
      switch (action) {
        case "cleanup":
          await executeCleanup(target, insight);
          break;
        case "organize":
          await executeOrganization(target, insight);
          break;
        case "archive":
          await executeArchive(target, insight);
          break;
        case "analyze":
          await executeAnalysis(target, insight);
          break;
        default:
          console.log(`Unknown action: ${action} on ${target}`);
      }

      onAction(action, target, getFilesByCategory(target));
    } catch (error) {
      console.error(`Failed to execute ${action} on ${target}:`, error);
    } finally {
      setSelectedAction(null);
      setActionProgress((prev) => ({ ...prev, [`${action}-${target}`]: 100 }));
    }
  };

  const analyzeDependencies = async (
    action: string,
    target: string,
    insight: PredictiveInsight
  ) => {
    setAnalyzingDependencies(true);

    try {
      // Build dependency graph if not already built
      await dependencyCheckerService.buildDependencyGraph(files);

      // Get target files for the action
      const targetFiles = getTargetFilesForAction(action, target, insight);

      // Analyze impact
      const analysis = await dependencyCheckerService.analyzeActionImpact(action, targetFiles);
      setDependencyAnalysis(analysis);

      console.log("Dependency analysis complete:", analysis);
    } catch (error) {
      console.error("Failed to analyze dependencies:", error);
    } finally {
      setAnalyzingDependencies(false);
    }
  };

  const getTargetFilesForAction = (
    action: string,
    target: string,
    insight: PredictiveInsight
  ): string[] => {
    const categoryFiles = getFilesByCategory(target);

    switch (action) {
      case "cleanup":
        return categoryFiles
          .filter((file) => {
            // Include temp files, duplicates, old files
            return (
              file.path?.includes("temp") ||
              file.path?.includes("tmp") ||
              file.size === 0 ||
              (file.lastModified && Date.now() - file.lastModified > 365 * 24 * 60 * 60 * 1000)
            );
          })
          .map((file) => file.path);

      case "archive":
        return categoryFiles
          .filter((file) => file.size > 10 * 1024 * 1024) // Files > 10MB
          .sort((a, b) => (b.size || 0) - (a.size || 0))
          .slice(0, 20)
          .map((file) => file.path);

      case "organize":
        return categoryFiles.map((file) => file.path);

      case "delete":
        return categoryFiles
          .filter((file) => file.path?.includes("temp") || file.path?.includes("tmp"))
          .map((file) => file.path);

      default:
        return categoryFiles.map((file) => file.path);
    }
  };

  const executeActionWithConfirmation = async (action: string, alternative?: string) => {
    const actualAction = alternative || action;

    // Execute the action
    switch (actualAction) {
      case "cleanup":
        await executeCleanup(dependencyAnalysis?.targetFiles[0]?.split("/")[0] || "", {} as any);
        break;
      case "organize":
        await executeOrganization(
          dependencyAnalysis?.targetFiles[0]?.split("/")[0] || "",
          {} as any
        );
        break;
      case "archive":
        await executeArchive(dependencyAnalysis?.targetFiles[0]?.split("/")[0] || "", {} as any);
        break;
      case "move":
        await executeMove(dependencyAnalysis?.targetFiles[0]?.split("/")[0] || "", {} as any);
        break;
      default:
        console.log(`Executing alternative action: ${actualAction}`);
    }

    // Hide dependency analysis after execution
    setShowDependencyAnalysis(false);
    setDependencyAnalysis(null);
  };

  const executeCleanup = async (target: string, insight: PredictiveInsight) => {
    const targetFiles = getFilesByCategory(target);

    // Simulate cleanup progress
    for (let i = 0; i <= 100; i += 10) {
      setActionProgress((prev) => ({ ...prev, [`cleanup-${target}`]: i }));
      await new Promise((resolve) => setTimeout(resolve, 100));
    }

    console.log(`Cleaned up ${targetFiles.length} files from ${target} category`);
  };

  const executeOrganization = async (target: string, insight: PredictiveInsight) => {
    const targetFiles = getFilesByCategory(target);

    // Simulate organization progress
    for (let i = 0; i <= 100; i += 20) {
      setActionProgress((prev) => ({ ...prev, [`organize-${target}`]: i }));
      await new Promise((resolve) => setTimeout(resolve, 150));
    }

    console.log(`Organized ${targetFiles.length} files in ${target} category`);
  };

  const executeArchive = async (target: string, insight: PredictiveInsight) => {
    const targetFiles = getHighImpactFiles(target);

    // Simulate archive progress
    for (let i = 0; i <= 100; i += 25) {
      setActionProgress((prev) => ({ ...prev, [`archive-${target}`]: i }));
      await new Promise((resolve) => setTimeout(resolve, 200));
    }

    console.log(`Archived ${targetFiles.length} large files from ${target} category`);
  };

  const executeAnalysis = async (target: string, insight: PredictiveInsight) => {
    // Simulate deep analysis progress
    for (let i = 0; i <= 100; i += 10) {
      setActionProgress((prev) => ({ ...prev, [`analyze-${target}`]: i }));
      await new Promise((resolve) => setTimeout(resolve, 100));
    }

    console.log(`Analyzed ${target} category for detailed insights`);
  };

  const executeMove = async (target: string, insight: PredictiveInsight) => {
    const targetFiles = getFilesByCategory(target);

    // Simulate move progress
    for (let i = 0; i <= 100; i += 20) {
      setActionProgress((prev) => ({ ...prev, [`move-${target}`]: i }));
      await new Promise((resolve) => setTimeout(resolve, 150));
    }

    console.log(`Moved ${targetFiles.length} files from ${target} category`);
  };

  const getRecommendedActions = (insight: PredictiveInsight, category: string) => {
    const actions: {
      type: string;
      label: string;
      description: string;
      priority: "high" | "medium" | "low";
    }[] = [];

    switch (insight.type) {
      case "growth":
        if (insight.reasoning.trendAnalysis.direction === "increasing") {
          actions.push({
            type: "cleanup",
            label: "Smart Cleanup",
            description: `Remove unnecessary ${category} files to slow growth`,
            priority: "high",
          });
          actions.push({
            type: "archive",
            label: "Archive Large Files",
            description: `Move large ${category} files to archive storage`,
            priority: "medium",
          });
        }
        break;

      case "cleanup":
        actions.push({
          type: "cleanup",
          label: "Quick Cleanup",
          description: `Remove temp and unnecessary ${category} files`,
          priority: "high",
        });
        break;

      case "organization":
        actions.push({
          type: "organize",
          label: "Auto-Organize",
          description: `Create subfolders and organize ${category} files`,
          priority: "medium",
        });
        break;

      case "security":
        actions.push({
          type: "analyze",
          label: "Security Scan",
          description: `Analyze ${category} files for security risks`,
          priority: "high",
        });
        break;
    }

    return actions;
  };

  const getPriorityColor = (priority: "high" | "medium" | "low") => {
    switch (priority) {
      case "high":
        return "#ef4444";
      case "medium":
        return "#f59e0b";
      case "low":
        return "#22c55e";
      default:
        return "#6b7280";
    }
  };

  if (!insights || insights.length === 0) {
    return (
      <div className="actionable-prediction-container">
        <BrainCircuit size={48} className="actionable-no-insights-icon" />
        <h3 className="actionable-no-insights-text">No Actionable Insights Available</h3>
        <p className="actionable-no-insights-text">
          Run more analyses to generate actionable predictions
        </p>
      </div>
    );
  }

  return (
    <div className="actionable-prediction-container">
      {/* Dependency Analysis Modal */}
      {showDependencyAnalysis && dependencyAnalysis && (
        <div className="actionable-modal-overlay">
          <div className="actionable-modal">
            <div className="actionable-modal-header">
              <h2 className="actionable-modal-title">Dependency Impact Analysis</h2>
              <button
                onClick={() => setShowDependencyAnalysis(false)}
                className="actionable-close-btn"
                aria-label="Close dependency analysis"
              >
                <X size={20} />
              </button>
            </div>
            <DependencyImpactAnalyzer
              analysis={dependencyAnalysis}
              onExecuteAction={executeActionWithConfirmation}
              loading={analyzingDependencies}
            />
          </div>
        </div>
      )}

      {insights.map((insight, index) => {
        const category = extractCategoryFromReasoning(insight.reasoning);
        const categoryFiles = getFilesByCategory(category);
        const highImpactFiles = getHighImpactFiles(category);
        const recommendedActions = getRecommendedActions(insight, category);

        return (
          <div key={index} className="glass-panel actionable-category-panel">
            {/* Header */}
            <div className="actionable-category-header">
              <div className="actionable-category-icon">{getCategoryIcon(category)}</div>
              <h4 className="actionable-category-title">
                {category.charAt(0).toUpperCase() + category.slice(1)} Category
              </h4>
              <div className="actionable-category-stats">
                <div className="actionable-stat-item">
                  <span className="actionable-stat-label">Files</span>
                  <span className="actionable-stat-value">{categoryFiles.length}</span>
                </div>
                <div className="actionable-stat-item">
                  <span className="actionable-stat-label">Total Size</span>
                  <span className="actionable-stat-value">
                    {(categoryFiles.reduce((sum, f) => sum + f.size, 0) / 1024 / 1024).toFixed(1)}MB
                  </span>
                </div>
                <div className="actionable-stat-item">
                  <span className="actionable-stat-label">Large Files</span>
                  <span className="actionable-stat-value">{highImpactFiles.length}</span>
                </div>
              </div>
            </div>

            {/* Primary Driver */}
            <div className="actionable-primary-driver">
              <h5 className="actionable-primary-driver-title">Primary Driver</h5>
              <div className="actionable-primary-driver-content">
                <AlertTriangle size={14} className="actionable-primary-driver-icon" />
                {insight.reasoning.primaryFactor}
              </div>
            </div>

            {/* Actionable Items */}
            <div className="actionable-actions">
              <h5 className="actionable-actions-title">Recommended Actions</h5>
              <div className="actionable-actions-list">
                {recommendedActions.map((action, actionIndex) => (
                  <div key={actionIndex} className="actionable-action-item">
                    <div className="actionable-action-icon">{getActionIcon(action.type)}</div>
                    <div className="actionable-action-content">
                      <h6 className="actionable-action-title">{action.label}</h6>
                      <p className="actionable-action-description">{action.description}</p>
                    </div>
                    <div className="actionable-action-priority">
                      <span className={`actionable-priority-${action.priority}`}>
                        {action.priority}
                      </span>
                      <button
                        onClick={() => executeAction(action.type, category, insight)}
                        disabled={
                          selectedAction === `${action.type}-${category}` || analyzingDependencies
                        }
                        style={{
                          padding: "0.5rem 1rem",
                          borderRadius: "6px",
                          background:
                            selectedAction === `${action.type}-${category}` ? "#6b7280" : "#3b82f6",
                          color: "white",
                          border: "none",
                          cursor:
                            selectedAction === `${action.type}-${category}` || analyzingDependencies
                              ? "not-allowed"
                              : "pointer",
                          fontSize: "0.875rem",
                          fontWeight: "bold",
                          display: "flex",
                          alignItems: "center",
                          gap: "0.5rem",
                          position: "relative",
                        }}
                      >
                        {selectedAction === `${action.type}-${category}` ? (
                          <>
                            <div
                              style={{
                                width: "12px",
                                height: "12px",
                                border: "2px solid white",
                                borderTop: "2px solid transparent",
                                borderRadius: "50%",
                                animation: "spin 1s linear infinite",
                              }}
                            />
                            {actionProgress[`${action.type}-${category}`] || 0}%
                          </>
                        ) : analyzingDependencies ? (
                          <>
                            <GitBranch size={14} />
                            Analyzing Dependencies...
                          </>
                        ) : (
                          <>
                            {getActionIcon(action.type)}
                            Execute
                            {["delete", "move", "archive"].includes(action.type) && (
                              <Shield size={12} style={{ marginLeft: "0.25rem" }} />
                            )}
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* High Impact Files Preview */}
            {highImpactFiles.length > 0 && (
              <div>
                <h5
                  style={{
                    margin: "0 0 1rem 0",
                    color: "var(--text-primary)",
                    fontSize: "0.875rem",
                  }}
                >
                  High Impact Files (Top {highImpactFiles.length})
                </h5>
                <div
                  style={{
                    display: "grid",
                    gap: "0.5rem",
                    maxHeight: "200px",
                    overflowY: "auto",
                  }}
                >
                  {highImpactFiles.slice(0, 5).map((file, fileIndex) => (
                    <div
                      key={fileIndex}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "0.5rem",
                        padding: "0.5rem",
                        background: "rgba(107, 114, 128, 0.1)",
                        borderRadius: "4px",
                        fontSize: "0.75rem",
                      }}
                    >
                      {getCategoryIcon(file.category || "unknown")}
                      <span style={{ flex: 1, color: "var(--text-primary)" }}>
                        {file.path?.split(/[/\\]/).pop() || file.name}
                      </span>
                      <span style={{ color: "var(--text-secondary)" }}>
                        {(file.size / (1024 * 1024)).toFixed(1)}MB
                      </span>
                    </div>
                  ))}
                  {highImpactFiles.length > 5 && (
                    <div
                      style={{
                        textAlign: "center",
                        color: "var(--text-secondary)",
                        fontSize: "0.75rem",
                        padding: "0.5rem",
                      }}
                    >
                      ... and {highImpactFiles.length - 5} more files
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
};

export default ActionablePrediction;
